export const siteConfig = {
  name: "Emmanuel Simbulan",
  title: "Emmanuel Simbulan — Business Analyst & Software Engineer",
  description:
    "Personal portfolio of Emmanuel Simbulan. Business Analyst & Software Engineer building technology that connects business and people.",
  url: "https://emmanuelsimbulan.dev",
  basePath: "/EmmanuelSimbulan",
  author: "Emmanuel Simbulan",
  email: "emmanuelrsimbulan@gmail.com",
  github: "https://github.com/emmanuelsimbulan",
  linkedin: "https://www.linkedin.com/in/emmanuel-simbulan/",
  twitter: "@emmanuelsimbulan",
  location: "Philippines",
  resumeUrl: "/resume.pdf",
  ogImage: "/og.png",
  navItems: [
    { label: "About", href: "#about" },
    { label: "Journey", href: "#journey" },
    { label: "Experience", href: "#experience" },
    { label: "Skills", href: "#skills" },
    { label: "Projects", href: "#projects" },
    { label: "Blog", href: "#blog" },
    { label: "Contact", href: "#contact" },
  ],
};
